# Generated by Django 5.1.7 on 2025-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StolenVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Biển số')),
                ('color', models.CharField(max_length=50, verbose_name='Màu xe')),
                ('model', models.CharField(max_length=100, verbose_name='Model xe')),
                ('reported_date', models.DateField(verbose_name='Ngày báo mất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
